apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
    spec:
      containers:
      - name: user_service
        image: user_service
